### ISSUE TITLE
Switch to canvas-prebuilt ?

### ISSUE THREAD

**Issue by piercus** [vmpowerio/chartjs-node#45]
Hello,

This is more an idea than an issue.

I would like to suggest using [canvas-prebuilt](https://www.npmjs.com/package/canvas-prebuilt) rather than canvas as a dependency.

This will make this library more 'portable' and speed up the installation.

What do you think ?

**Comment by olliejm** [comment]
What is required for canvas-prebuilt support? I cloned repo and changed `canvas` to `canvas-prebuilt` in `package.json`, then altered `require('canvas')` in `index.js` to `require('canvas-prebuilt')` ... problem is however that then when I run a test script (which worked fine when using regular canvas), I get the following error:

```
Unhandled rejection TypeError: Cannot read property 'length' of null
    at Object.acquireContext (C:\Users\Administrator\chart-server\node_modules\chartjs-node\node_modules\chart.js\src\platforms\platform.dom.js:340:19)
    at Chart.construct (C:\Users\Administrator\chart-server\node_modules\chartjs-node\node_modules\chart.js\src\core\core.controller.js:79:27)
    at new Chart (C:\Users\Administrator\chart-server\node_modules\chartjs-node\node_modules\chart.js\src\core\core.js:42:8)
    at jsdom.envAsync.then.window (C:\Users\Administrator\chart-server\node_modules\chartjs-node\index.js:106:31)
... [continues but mostly irrelevant I think]
```

Is it possible to add this support manually on my side at all?

**Comment by JTBrinkmann** [comment]
for the record, the regular `canvas` package now also comes prebuilt, so there's no use in switching

**Comment by piercus** [comment]
@JTBrinkmann thanks for the update, i'm closing the issue then
