### ISSUE TITLE
TypeError: Cannot read property 'plugins' of undefined

### ISSUE THREAD

**Issue by Prior99** [vmpowerio/chartjs-node#51]
I am getting the following error when using this library:
```
Unhandled rejection TypeError: Cannot read property 'plugins' of undefined
    at jsdom.envAsync.then.window (/home/prior/repositories/node-libpng/benchmark/node_modules/chartjs-node/index.js:86:43)
    at tryCatcher (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/promise.js:638:18)
    at Object.done (/home/prior/repositories/node-libpng/benchmark/node_modules/bluebird/js/release/nodeback.js:42:21)
    at process.nextTick (/home/prior/repositories/node-libpng/benchmark/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

My code looks like this:
```
        const colors = ["rgb(255, 128, 0)", "rgb(80, 80, 255)"];
        const options = {
            labels: ["Decode"],
            xAxes: [
                {
                    scaleLabel: {
                        display: true,
                        labelString: "OP/s (higher is better)"
                    }
                }
            ],
            datasets: suite.map((benchmark, index) => {
                return {
                    label: benchmark.name,
                    backgroundColor: colors[index],
                    data: [benchmark.hz]
                };
            })
        };
        const chartNode = new ChartjsNode(1000, 200);
        chartNode.drawChart(options)
            .then(() => chartNode.getImageBuffer('image/png'))
            .then(buffer => chartNode.getImageStream('image/png'))
            .then(streamResult => chartNode.writeImageToFile('image/png', './benchmark.png'))
            .catch(err => {
                console.error("Error drawing chart", err);
            })
```

Versions used:
```
    "chart.js": "2.6",
    "chartjs-node": "^1.6.1",
```

**Comment by Prior99** [comment]
Nevermind, it needs to be `chartNode.drawChart({ options })`. Sorry for causing disturbances.

**Comment by coolioxlr** [comment]
I am still having the same issue after adding chartNode.drawChart({ options })
