### ISSUE TITLE
502 Bad Gateway on the demo website

### ISSUE THREAD

**Issue by eko24ive** [vmpowerio/chartjs-node#57]
![image](https://user-images.githubusercontent.com/25591824/41345592-d22136b6-6f0c-11e8-8cb7-f27d791ac20f.png)

**Comment by williamdes** [comment]
No 502 error, but an error:
```
TypeError: Cannot read property 'data' of undefined at Layer.module.exports [as handle] (/middleware/routes/validators/apply-permissions.js:38:20) at trim_prefix (/node_modules/express/lib/router/index.js:254:17) at /node_modules/express/lib/router/index.js:216:9 at param (/node_modules/express/lib/router/index.js:305:14) at param (/node_modules/express/lib/router/index.js:321:14) at Function.proto.process_params (/node_modules/express/lib/router/index.js:365:3) at next (/node_modules/express/lib/router/index.js:207:19) at next (/node_modules/express/lib/router/index.js:182:38) at next (/node_modules/express/lib/router/index.js:182:38) at next (/node_modules/express/lib/router/index.js:182:38) at next (/node_modules/express/lib/router/index.js:182:38) at next (/node_modules/express/lib/router/index.js:182:38) at next (/node_modules/express/lib/router/index.js:182:38) at Layer.logger (/node_modules/morgan/index.js:144:5) at trim_prefix (/node_modules/express/lib/router/index.js:254:17) at /node_modules/express/lib/router/index.js:216:9 at Function.proto.process_params (/node_modules/express/lib/router/index.js:286:12) at next (/node_modules/express/lib/router/index.js:207:19) at Layer.handle (/app.js:49:5) at trim_prefix (/node_modules/express/lib/router/index.js:254:17) at /node_modules/express/lib/router/index.js:216:9 at Function.proto.process_params (/node_modules/express/lib/router/index.js:286:12) at next (/node_modules/express/lib/router/index.js:207:19) at Layer.expressInit [as handle] (/node_modules/express/lib/middleware/init.js:23:5) at trim_prefix (/node_modules/express/lib/router/index.js:254:17) at /node_modules/express/lib/router/index.js:216:9 at Function.proto.process_params (/node_modules/express/lib/router/index.js:286:12) at next (/node_modules/express/lib/router/index.js:207:19)
```

**Comment by eko24ive** [comment]
You're correct, although as you can see at the time this issue was created mentioned error wasn't shown.

**Comment by williamdes** [comment]
@eko24ive Yes :)
