### ISSUE TITLE
./util/has_lib.sh: line 31: pkg-config: command not found

### ISSUE THREAD

**Issue by davidgatti** [vmpowerio/chartjs-node#76]
Hy, when I try to install the module under MacOS (latest version), I get the following error message.

```
./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/davidgatti/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/davidgatti/.nvm/versions/node/v10.13.0/bin/node" "/Users/davidgatti/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/davidgatti/Documents/GitHub/Retireryte/Rr-Lambda-Financial-Calculation/node_modules/chartjs-node/node_modules/canvas
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN chartjs-node@1.7.1 requires a peer of chart.js@<=2.7.* but none is installed. You must install peer dependencies yourself.
npm WARN financial-calculation@1.0.0 No repository field.
```

And I do have Cairo installed under MacOS

**Comment by connorgillis** [comment]
Any luck?

**Comment by digifoxman** [comment]
Yes, did someone find a solution for this?
